config/routes.rb
MoneyTeam::Application.routes.draw do

  devise_for :members, controllers: { registration: "auth/members/registrations",
                                      sessions:     "auth/members/sessions" }
  devise_scope :member do
    get  "/welcome"   => "auth/members/registrations#new"

    get  "/register"  => "auth/members/registrations#new"
    post "/register"  => "auth/members/registrations#create", as: :member_registration
    put  "/member/account/update"=> "auth/members/registrations#update"
    get  "/login"     => 'auth/members/sessions#new',    as: :new_member_session
    post "/login"     => 'auth/members/sessions#create', as: :member_session
  end

  # application
  scope module: :app do
    # user hub
    namespace :hub do
      resource  :account, path_names: { edit: :settings }
      resources :groups,        only: [ :index, :new, :create ],  path: "teams"
      resources :cycles,        only: :index
      resources :notifications, only: :index
      resources :messages,      except: [ :edit, :update ]
      resources :payments,      only: :index, path: "money"

      root to: "dashboard#show"
    end

    # teams
    scope module: :groups do
      resources :groups, path: "teams", path_names: { edit: :settings } do
        member do
          get  "members/join" => "groups#add_member",     as: :add_member
          put  "leave"        => "groups#remove_member",  as: :remove_member
          get  "rounds/start" => "groups#start_round",    as: :start_round
          get  "rounds/pause" => "groups#pause_round",    as: :pause_round
          get  "rounds/stop"  => "groups#stop_round",     as: :stop_round
          get  "current"      => "groups#current_cycle",  as: :current_cycle
        end

        resources :memberships, only: :update_multiple do
          put "update_multiple", on: :collection
        end
        resources :cycles, only: [ :show, :index ] do
          member do
            put "take_payment" => "cycles#acknowledge_payment", as: :acknowledge_payment
          end
        end
        resources :invites, only: [ :create, :destroy ]
        resources :members, only: [ :show, :index ]
        resources :reports, only: [ :show ]
      end
    end
  end


  # admin console
  namespace :admin do
  end


  # website
  scope module: :site do
    resources :groups, as: :site_groups, path: "welcome/teams", only: :create
    # do
    #   get "join", on: :member
    # end
    get   "homepage" => "pages#home"
    match "/"        => "pages#coming_soon"
  end

  root to: "site/pages#coming_soon"
end

=begin
  resources :groups, :path => "teams", path_names: { edit: :settings } do
    member do
      get  "join"
      get  "members/join" => "groups#add_member",     as: :add_member
      put  "leave"        => "groups#remove_member",  as: :remove_member
      post "rounds/start" => "groups#start_round",    as: :start_round
      get  "current"      => "groups#current_cycle",  as: :current_cycle
    end
    resources :cycles, only: [ :show, :index ] do
      put "payment_made" => "cycles#payment_made", as: :payment_made
    end
    resources :invites, only: [ :new, :create ]
    resources :members, only: [ :show, :index ]
    resources :memberships, only: :update_multiple do
      put "update_multiple", on: :collection
    end
  end
=end

=begin
  namespace :accounts, :path => "/hub" do
    resources :groups,        :only   => [ :index, :new, :create ],  :path => "teams"
    resources :cycles,        :only   => :index
    resources :notifications, :only   => :index
    resources :messages,      :except => [ :edit, :update ]

    root :to => "accounts#show", :as => :hub
  end
=end

# get     '/login'        => 'auth/bank_admins/sessions#new',         :as => :new_bank_admin_session
# post    '/login'        => 'auth/bank_admins/sessions#create',      :as => :bank_admin_session
# delete  '/logout'       => 'auth/bank_admins/sessions#destroy',     :as => :destroy_bank_admin_session
# get     '/account'      => 'auth/bank_admins/registrations#show',   :as => :bank_admin_registration
# get     '/account/settings' => 'auth/bank_admins/registrations#edit',   :as => :edit_bank_admin_registration
# put     '/account'      => 'auth/bank_admins/registrations#update'
# post    '/account'      => 'auth/bank_admins/registrations#create', :as => :bank_admin_registration

app/controllers/accounts/groups_controller.rb
class Accounts::GroupsController < Accounts::BaseController


  def index
    @groups = current_member.groups
  end



  def new
    @group = Group.new
  end



  def create
    @group = Group.new(params[:group])

    if @group.save && @group.add_member(current_member)
      flash[:success] = "You've started a new team!"
      redirect_to group_url(@group)
    else
      flash[:error] = @group.errors.full_messages
      render :action => "new"
    end
  end


end

app/controllers/app/groups/base_controller.rb
class App::Groups::BaseController < App::AppController

  before_filter :load_group


  protected


  def load_group
    find_group
    verify_group_access!
  end


  def find_group
    @group = Group.find_by_id(params[:group_id] || params[:id])

    unless @group
      flash[:alert] = "Group doesn't exist"
      redirect_to member_signed_in? ? hub_root_url : root_url and return
    end
  end


  # Checks permissions of member trying to access page
  # Adds member if team has no members yet
  def verify_group_access!
    if @group.has_members?
      unless current_member.is_group_member?(@group) ||
               @group.invited?(current_member.email)
        redirect_to hub_root_url, alert: "You do not have access to #{ @group.name }!"
      end
    else
      flash.clear
      flash[:success] = "Welcome to Team #{ @group.name }!"
      @group.add_member(current_member)
    end

  end

end

app/controllers/app/groups/cycles_controller.rb
class App::Groups::CyclesController < App::Groups::BaseController


  def index
    @rounds = @group.cycles.group_by(&:round)
  end


  def show
    @cycle = @group.cycles.find(params[:id])
  end


  # PUT
  def acknowledge_payment
    @cycle   = @group.cycles.find(params[:id])
    @payment = @cycle.payments.find(params[:p_id])

    if @cycle.acknowledge_payment(@payment)
      # @payment.create_activity action: 'register', owner: @group
      flash[:success] = "Payment information saved successfully"
    else
      flash[:error] = "Payment could not be saved"
    end

    redirect_to group_url(@group)
  end
end

app/controllers/app/groups/groups_controller.rb
class App::Groups::GroupsController < App::Groups::BaseController
  # include PublicActivity::StoreController

  # view all public groups, have to be logged in tho
  # groups will have to be marked public and private
  def index
    @groups = Group.all
  end


  def show
    @latest_cycle       = @group.latest_cycle
    @group_invites      = @group.invites
    @group_cycles       = @group.cycles
    @payment_cycle_unit = @group.payment_cycle_unit
    @cycle_status       = @group.in_session? && @latest_cycle.present?
    @activities         = PublicActivity::Activity.order("created_at desc").
                            includes(:trackable).
                            where(owner_id: @group.id)
    @active             = params[:active]
  end


  def edit
    @admin       = current_member.is_group_admin?(@group)
    @not_running = !@group.in_session?
  end


  def update
    if @group.update_attributes(params[:group])
      flash[:success] = "Rules successfully updated!"
      redirect_to group_url(@group)
    else
      flash[:error] = "Error changing group settings!"
      render action: "edit "
    end
  end


  # GET members/join"
  def add_member
    op = @group.add_member(current_member)

    if op[:status] == true
      flash[:success] = "Congratulations! You are now a member of #{ @group.name }."
    else
      flash[:error] = "Could not add member! #{op[:error]}"
    end

    redirect_to group_url(@group)
  end


  # PUT leave
  def remove_member
    op = @group.remove_member(current_member)

    if op[:status] == true
      flash[:success] = "You have successfully left #{ @group.name }!"
      redirect_to hub_root_url(@group) and return
    else
      flash[:error] = "Could not leave team! #{op[:error]}"
      redirect_to group_url(@group)
    end
  end


  # Starts a new round of cycles
  # GET rounds/start
  def start_round
    if @group.start_new_cycle(@group.latest_cycle)
      flash[:notice] = "Round #{ @group.round } started!"
      # redirect_to current_cycle_group_url(@group)
      redirect_to group_url(@group)
    else
      flash[:error] = "New round couldn't be started!"
      redirect_to group_url(@group)
    end
  end



  # GET rounds/pause
  def pause_round
    flash[:success] = "Pause nigguh"
    redirect_to group_url(@group)
  end



  # GET rounds/stop
  def stop_round
    flash[:success] = "Stop nigguh"
    redirect_to group_url(@group)
  end


  # GET current
  def current_cycle
    @cycle = @group.latest_cycle
    redirect_to group_url unless @cycle
  end
end

app/controllers/app/groups/invites_controller.rb
class App::Groups::InvitesController < App::Groups::BaseController


  def create
    op = @group.create_invite_for(params[:invite])

    if op[:status] == true
      flash[:success] = "Invite sent!"
    else
      flash[:error] = "Could not send invite! #{op[:error]}"
    end

    redirect_to group_url(@group, active: 'members')
  end


  def destroy
    @invite = @group.invites.find(params[:id])
    @invite.destroy

    flash[:success] = "Invite revoked"
    redirect_to group_url(@group, active: 'members')
  end

end

app/controllers/app/groups/members_controller.rb
class App::Groups::MembersController < App::Groups::BaseController


  def show
    @member = @group.members.find(params[:id])
  end


  def index; end

end

app/controllers/app/groups/memberships_controller.rb
class App::Groups::MembershipsController < App::Groups::BaseController


  def update_multiple
    values = params[:memberships].values.collect{|m| m['cycle_position']}
    if values.uniq.length == values.length
      params[:memberships].each do |value|
        new_position = value[1][:cycle_position]
        membership   = @group.memberships.find(value[0])
        if membership
          current_position = membership.cycle_position
          unless current_position.to_s == new_position.to_s
            if membership.update_attributes(cycle_position: new_position)
              membership.create_activity action: 'change_position',
                                         params: { previous_position: current_position },
                                         owner: @group,
                                         recipient: membership.member
            end
          end
        end
      end
      flash[:success] = "Positions updated successfully"
    else
      flash[:error] = "Only one member can occupy a specific position at one time"
    end
    redirect_to group_url(@group)
  end
end

app/controllers/app/hub/groups_controller.rb
class App::Hub::GroupsController < App::Hub::BaseController

  def index
    @groups = current_member.groups
  end


  def new
    @group = Group.new
  end


  def create
    @group = Group.new(params[:group])

    if @group.save && @group.add_member(current_member)
      flash[:success] = "You've started a new team!"
      redirect_to group_url(@group)
    else
      flash[:error] = @group.errors.full_messages
      render action: "new"
    end
  end

end

app/helpers/accounts/groups_helper.rb
module Accounts::GroupsHelper
end

app/helpers/app/groups/base_helper.rb
module App::Groups::BaseHelper
end

app/helpers/app/groups/cycles_helper.rb
module App::Groups::CyclesHelper
end

app/helpers/app/groups/groups_helper.rb
module App::Groups::GroupsHelper
end

app/helpers/app/groups/invites_helper.rb
module App::Groups::InvitesHelper
end

app/helpers/app/groups/members_helper.rb
module App::Groups::MembersHelper
end

app/helpers/app/groups/memberships_helper.rb
module App::Groups::MembershipsHelper
end

app/helpers/app/hub/groups_helper.rb
module App::Hub::GroupsHelper
end

app/views/app/groups/groups/_form.html.erb
<fieldset>
<div class="control-group">
<label class="control-label" for="input">Team Name</label>
<div class="controls">
  <%= f.text_field :name,
    placeholder: "The A-Team",
    class: "input-xlarge" %>
  <p class="help-block">Pick a cool name for your team </p>
</div>
</div>

<div class="control-group">
<label class="control-label" for="textarea">Team Description</label>
<div class="controls">
  <%= f.text_area :description, placeholder: "We the best...", class: "input-xlarge", rows: 2 %>
</div>
</div>

<div class="control-group">
<label class="control-label" for="input">Payments</label>
<div class="controls">

<div class="form-controls">
<div class="input-prepend input-append">
<span class="add-on">Members pay </span>
<%= f.text_field :cycle_amount, placeholder: "20", style: "width:40px" %>
<span class="add-on">every</span>
<%= f.text_field :payment_cycle_quantity, placeholder: "1", style: "width:30px" %>
<%= f.select :payment_cycle_unit,
  options_for_select(Group.pretty_cycle_units,
                     selected: "months"), {},
                     {style: "width:90px;vertical-align:top;height:32px"} %>
<span class="add-on">&nbsp;</span>
</span>
</div>
</div>
</div>
</div>

<div class="control-group">
<label class="control-label" for="input">Penalties</label>
<div class="controls">
<div class="form-controls">
<div class="input-prepend input-append">
<span class="add-on">Members must pay a penalty of </span>
<%= f.text_field :penalty_amount, placeholder: "2", style: "width:40px" %>
<span class="add-on">if their payment</span>
</span>
</div>
</div>

<br/>

<div class="form-controls">
<div class="input-prepend input-append">
<span class="add-on">is not received </span>
<%= f.text_field :penalty_cycle_quantity, placeholder: "1", style: "width:30px" %>
<%= f.select :penalty_cycle_unit,
  options_for_select(Group.pretty_cycle_units,
                     selected: "weeks"), {},
                     {style: "width:90px;vertical-align:top;height:32px"} %>
<span class="add-on"> after a new cycle starts.</span>
</div>
</div>


</div>
</div>
<div class="control-group">
<label class="control-label" for="input">Alerts</label>
<div class="controls">
<div class="form-controls">
<div class="input-prepend input-append">
<span class="add-on">Defaulting members are alerted </span>

<%= f.text_field :penalty_alert_timespan_quantity, placeholder: "1", style: "width:30px" %>
<%= f.select :penalty_alert_timespan_unit,
  options_for_select(Group.pretty_cycle_units,
                     selected: "days"), {},
                     {style: "width:90px;vertical-align:top;height:32px"} %>

<span class="add-on">before the deadline</span>
</span>
</div>
</div>
</div>
</div>

</fieldset>

app/views/app/groups/groups/_quick_stats.html.erb
<div class="page-header-1">
<div class="pull-left">
<h1><%= @group.name %></h1>
</div>
<div class="pull-right">

<ul class="stats">
  <% if @group.in_session? %>
<li class="lime">
<i class="icon-spinner"></i>
<div class="details">
<span class="big">
  <strong> Round <%= @group.round %> </strong>
  Cycle <%= @group.latest_cycle.number %>
</span>
<span>Status: <strong>In Session</strong></span>
</div>
</li>
  <% else %>
<li class="red">
<i class="icon-stop"></i>
<div class="details">
<span class="big">&nbsp;</span>
<span>Status: <strong>Stopped</strong></span>
</div>
</li>
  <% end %>

<!--
<li class="magenta">
<i class="icon-shopping-cart"></i>
<div class="details">
<span class="big">175</span>
<span>New orders</span>
</div>
</li>
<li class='satgreen'>
<i class="icon-money"></i>
<div class="details">
<span class="big">$324,12</span>
<span>Balance</span>
</div>
</li>
-->

<% if @group.in_session? %>
  <% if @group.latest_cycle.last? %>
<li class='lightred'>
<i class="icon-calendar"></i>
<div class="details">
<span class="big"><%= @group.latest_cycle.end_date.to_s(:long) %></span>
<span> Round Ends</span>
</div>
</li>
  <% else %>
<li class='orange'>
<i class="icon-calendar"></i>
<div class="details">
<span class="big"><%= @group.latest_cycle.next_cycle_start_date.to_s(:long) %></span>
<span>Next Cycle <%= @group.latest_cycle.number + 1 %> Begins</span>
</div>
</li>
  <% end %>
<% end %>
</ul>

</div>
</div>

app/views/app/groups/groups/_session_warning.html.erb
<center>
<h3>
<span style="font-size:100px" class="awe-exclamation-sign"></span><br/>
<%= message %>.</h3
</h3>
</center>

app/views/app/groups/groups/_sidebar.html.erb
<ul class="tiles">

<li class="blue <%= "white" if current_page? group_path(group) %>">
<a href="<%= group_path(group) %>">
<span class="count"><i class="icon-dashboard"></i></span>
<span class="name">Dashboard</span></a>
</li>

<% if false %>
<li class="blue <%= "white" if current_page? group_members_path(group) %>">
<a href="<%= group_members_path(group) %>">
<span class="count"><i class="icon-user"></i> <%= group.members.count %></span>
<span class="name">Members</span>
</a>
</li>
<% end %>

<!--
<li class="blue">
<a href="components-tiles.html#">
<span class="count"><i class="icon-comments-alt"></i> 4</span>
<span class="name">Messages</span>
</a>
</li>
-->

<li class="blue <%= "white" if current_page? group_cycles_path(group) %>">
<a href="<%= group_cycles_path(group) %>">
<span class="count"><i class="icon-time"></i></span>
<span class="name">History</span>
</a>
</li>

<li class="blue <%= "white" if current_page? edit_group_path(group) %>">
<a href="<%= edit_group_path(group) %>">
<span><i class="icon-wrench"></i></span>
<span class="name">Settings</span>
</a>
</li>

<% unless group.in_session? %>
  <% if current_member.is_group_member?(group) %>
  <% unless current_member.is_group_admin?(group) %>
<li class="red">
<a href="components-tiles.html#">
<span><i class="icon-signout"></i></span>
<span class="name">Leave Group</span>
</a>
</li>
  <% end %>
  <% end %>
<% end %>

<!--
<li class="brown">
<a href="components-tiles.html#"><span class="count"><i class="icon-envelope"></i> 1</span><span class="name">Messages</span></a>
</li>
<li class="image">
<a href="components-tiles.html#"><img alt="" src="/img/demo/user-1.jpg"><span class="name">Jane Doe</span></a>
</li>
<li class="blue ">
<a href="components-tiles.html#"><span class="nopadding"><h5>@eakroko</h5><p>Check the new Flat theme on themeforest. Incredible fast and easy to use.</p></span><span class="name"><i class="icon-twitter"></i><span class="right">1min ago</span></span></a>
</li>
<li class="green ">
<a href="components-tiles.html#"><span><i class="icon-globe"></i></span><span class="name">User regions</span></a>
</li>
<li class="brown">
<a href="components-tiles.html#"><span class="count"><i class="icon-bolt"></i> 3</span><span class="name">Warnings</span></a>
</li>
<li class="magenta">
<a href="components-tiles.html#"><span><i class="icon-star"></i></span><span class="name">Ratings</span></a>
</li>
<li class="pink ">
<a href="components-tiles.html#"><span><i class="icon-money"></i></span><span class="name">Balance</span></a>
</li>
<li class="blue">
<a href="components-tiles.html#"><span><i class="icon-wrench"></i></span><span class="name">Optimize site</span></a>
</li>
<li class="red ">
<a href="components-tiles.html#"><span><i class="icon-eye-open"></i></span><span class="name">Preview changes</span></a>
</li>
-->
</ul>

app/views/app/groups/groups/current_cycle.html.erb
<%= render 'layout', :group => @group %>

This is the current cycle

<%= render 'cycles/cycle_details', :group => @group,
                                   :cycle => @cycle,
                                   :receiving_member => @cycle.receiving_member %>

app/views/app/groups/groups/edit.html.erb
<% if false %>
<%= render 'layout', :group => @group %>

<div class="row-fluid">
<div class="span12">
<div class="box box-bordered">
<div class="box-title">
<h3><i class="icon-th-list"></i> Team Rules</h3>

<% if @not_running %>
<div class="actions">
  <%= form_tag start_round_group_path(@group), :style => "margin:0;" do  -%>
    <button class="btn btn-primary" style="font-size:10px;"><i class="icon-play"></i> Start New Round</button>
  <% end -%>
</div>
<% end -%>

</div>
<div class="box-content nopadding">
<%= form_for @group, :html => { :class => "form-horizontal form-bordered" } do |f| -%>
<div class="control-group">
<label class="control-label" for="textfield">TEAM INFO</label>
<div class="controls">
    <% if @not_running && @admin %>
  Team <%= f.text_field :name %>
  <% else %>
  Team <%= @group.name %>
  <% end -%>
</div>
</div>

<div class="control-group">
  <label class="control-label" for="textfield">CONTRIBUTIONS </label>
  <div class="controls">
    <% if @not_running && @admin %>
    <div class="section">
      Each member pays
      <div class="input-append input-prepend">
      <span class="add-on">$</span>
      <%= f.text_field :cycle_amount,
        :class => "input-mini", :placeholder => "10", :size => 5 %>
      </div>
      every
      <%= f.text_field :payment_cycle_quantity,
        :class => "spinner input-mini" %>
      <span class="input-medium select-fix">
        <%= f.select :payment_cycle_unit,
          options_for_select(Group.pretty_cycle_units,
                             :selected => "months"),
                             {}, {:class => "chosen-select"} %>
      </span>
    </div>
    <div class="section">
      Currency used is
    </div>
    <% else %>
    <div class="section">
      Each member pays
      <strong>
      <%= @group.cycle_amount.to_money.format(:symbol => true) %>
      </strong>
      every
      <strong>
      <%= pluralize(@group.payment_cycle_quantity,
                    @group.payment_cycle_unit.to_s.chomp('s')) %>
      </strong>
    </div>

    <div class="section">
      Currency used is
    </div>
    <% end %>
  </div>
</div>

<div class="control-group">
  <label class="control-label" for="password">PENALTY</label>
  <div class="controls">
    <% if @not_running && @admin %>
    <div class="section">
      Members must pay a penalty of
      <div class="input-append input-prepend">
      <span class="add-on">$</span>
      <%= f.text_field :penalty_amount,
        :class => "input-mini", :placeholder => "10", :size => 5 %>
      </div>

      if their payment is not received
      <%= f.text_field :penalty_cycle_quantity,
        :class => "spinner input-mini" %>

      <span class="input-medium select-fix">
      <%= f.select :penalty_cycle_unit,
        options_for_select(Group.pretty_cycle_units,
                               :selected => "days"),
        {}, {:class => "chosen-select", :size => 10} %>
      </span>
      after the cycle starts.
    </div>
    <div class="section">
      Defaulting members are alerted
      <%= f.text_field :penalty_alert_timespan_quantity,
                    :class => "spinner input-mini" %>

      <span class="input-medium select-fix">
      <%= f.select :penalty_alert_timespan_unit,
        options_for_select(Group.pretty_cycle_units,
                           :selected => "days"),
        {}, {:class => "chosen-select"} %>
      </span>
       <span style="display:inline">
         before penalty deadline.
       </span>
    </div>
    <% else %>
    <div class="section">
      Members must pay a penalty of
      <strong>
      <%= @group.penalty_amount.to_money.format(:symbol => true) %>
      </strong>

      if their payment is not received
      <strong>
      <%= pluralize(@group.penalty_cycle_quantity,
                    @group.penalty_cycle_unit.to_s.chomp('s')) %>
      </strong>
      after the cycle starts
    </div>

    <div class="section">
      Defaulting members are alerted
      <strong>
      <%= pluralize(@group.penalty_alert_timespan_quantity,
                    @group.penalty_alert_timespan_unit.to_s.chomp('s')) %>
      </strong>
      before penalty deadline
    </div>
    <% end -%>
  </div>
</div>

<% if @not_running && @admin %>
<div class="form-actions" style="padding:0 160px">
  <%= f.submit "Save Changes", :class => "btn btn-primary" %>
</div>
<% end %>

<% end -%>



</div>
</div>
</div>
</div>

<div class="row-fluid">
<div class="span6">
<div class="box box-bordered">
<div class="box-title">
<h3><i class="icon-list-ol"></i>Positions</h3>
</div>

<div class="box-content nopadding">
<%= form_tag update_multiple_group_memberships_path(@group), :method => :put do |f| -%>
<table class="table table-user table-nohead">
<tbody>
<% for membership in @group.memberships.includes(:member).order(:cycle_position) -%>
  <%= fields_for "memberships[]", membership do |m| %>
  <tr>
  <td class='img'><img src="/img/demo/user-1.jpg" alt=""></td>
  <td class='user'> <%= membership.member.email %> </td>
  <td class='icon'>
    <% if @not_running && @admin %>
    <%= m.select :cycle_position,
    options_for_select(@group.memberships.map{|m| [m.cycle_position,
                                                   m.cycle_position]},
                                                   :selected => membership.cycle_position),
                                                   {}, {:class=>"input-mini"}  %>
    <% else %>
    <strong>
     <a style="color:#444" href="javascript:;" class='btn'><%= membership.cycle_position %></a>
    </strong>
    <% end %>
  </td>
  </tr>
  <% end -%>
<% end -%>
</tbody>
</table>
<% if @not_running && @admin %>
<div class="form-actions" style="padding-bottom:0;padding-left:10px">
  <%= submit_tag "Save Changes", :class => "btn btn-primary" %>
</div>
<% end %>
<% end -%>
</div>

</div>
</div>

<div class="span6">
<div class="box box-bordered">
<div class="box-title">
<h3><i class="icon-asterisk"></i>Invitations Sent</h3>

<% if @not_running && @admin %>
<div class="actions">
<%= link_to raw("Send Invite <i class='icon-plus'></i>"),
  new_group_invite_path(@group),
  :class => "btn btn-mini" %>
</div>
<% end %>


</div>

<div class="box-content nopadding">
<table class="table table-user table-nohead">
<tbody>
<% for invite in @group.invites -%>
  <tr>
  <td class='img'><img src="/img/demo/user-1.jpg" alt=""></td>
  <td class='user'> <%= invite.email %> </td>
  </tr>
<% end -%>
</tbody>
</table>
</div>

</div>
</div>
</div>


<% if false %>
<%= form_tag update_multiple_group_memberships_path(@group), :method => :put do |f| -%>
<table>
  <tr>
    <th>Email</th>
    <th>Position</th>
  </tr>
<% for membership in @group.memberships.includes(:member).order(:cycle_position) -%>
  <%= fields_for "memberships[]", membership do |m| %>
  <tr>
    <td> <%= membership.member.email %> </td>
    <td> <%= m.select :cycle_position,
      options_for_select(@group.memberships.map{|m| [m.cycle_position,
                                                     m.cycle_position]},
                         :selected => membership.cycle_position) %> </td>
  </tr>
  <% end -%>
<% end -%>
</table>
<%= submit_tag "Save Changes" %>
<% end -%>
<% end %>
<% end %>

app/views/app/groups/groups/index.html.erb
<h1> HOME PAGE </h1>

<% for group in @groups -%>
  <p> <%= link_to group.name, group_url(group) %> </p>
<% end -%>


<p> <%= link_to "Start New Group", new_group_path %> </p>

app/views/app/groups/groups/join.html.erb
<% if member_signed_in? %>

  <h2>  <%= @group.name %> </h2>

  <%= link_to "Join Group?", add_member_group_path(@group) %>


<% else %>

<div style="">
<div style="float:left">
<h2>Sign up</h2>

<%= form_for(resource,
             :as => resource_name,
             :url => registration_path(resource_name)) do |f| %>

  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <%= hidden_field_tag :group_id, @group.id %>

  <div><%= f.submit "Sign up" %></div>
<% end %>

<%= render "devise/shared/links" %>
</div>

<div style="float:right">
<h2>Sign in</h2>

<%= form_for(resource,
             :as => resource_name,
             :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <%= hidden_field_tag :group_id, @group.id %>
  <div><%= f.submit "Sign in" %></div>
<% end %>

<%= render "devise/shared/links" %>
</div>
</div>
<% end %>

app/views/app/groups/groups/new.html.erb
<%= flash.inspect %>

<%= form_for @group do |f| -%>

  <p> Group Name: <%= f.text_field :name %> </p>

  <p> Each member pays <%= f.text_field :cycle_amount %> </p>

  <p> every <%= f.text_field :payment_cycle_quantity %>
      <%= f.select :payment_cycle_unit,
          options_for_select(Group.pretty_cycle_units, :selected => "months") %> </p>

  <p> <%= f.submit "Save", :class => "btn btn-primary" %> </p>

<% end -%>