config/routes.rb
MoneyTeam::Application.routes.draw do

  devise_for :members, controllers: { registration: "auth/members/registrations",
                                      sessions:     "auth/members/sessions" }
  devise_scope :member do
    get  "/welcome"   => "auth/members/registrations#new"

    get  "/register"  => "auth/members/registrations#new"
    post "/register"  => "auth/members/registrations#create", as: :member_registration
    put  "/member/account/update"=> "auth/members/registrations#update"
    get  "/login"     => 'auth/members/sessions#new',    as: :new_member_session
    post "/login"     => 'auth/members/sessions#create', as: :member_session
  end

  # application
  scope module: :app do
    # user hub
    namespace :hub do
      resource  :account, path_names: { edit: :settings }
      resources :groups,        only: [ :index, :new, :create ],  path: "teams"
      resources :cycles,        only: :index
      resources :notifications, only: :index
      resources :messages,      except: [ :edit, :update ]
      resources :payments,      only: :index, path: "money"

      root to: "dashboard#show"
    end

    # teams
    scope module: :groups do
      resources :groups, path: "teams", path_names: { edit: :settings } do
        member do
          get  "members/join" => "groups#add_member",     as: :add_member
          put  "leave"        => "groups#remove_member",  as: :remove_member
          get  "rounds/start" => "groups#start_round",    as: :start_round
          get  "rounds/pause" => "groups#pause_round",    as: :pause_round
          get  "rounds/stop"  => "groups#stop_round",     as: :stop_round
          get  "current"      => "groups#current_cycle",  as: :current_cycle
        end

        resources :memberships, only: :update_multiple do
          put "update_multiple", on: :collection
        end
        resources :cycles, only: [ :show, :index ] do
          member do
            put "take_payment" => "cycles#acknowledge_payment", as: :acknowledge_payment
          end
        end
        resources :invites, only: [ :create, :destroy ]
        resources :members, only: [ :show, :index ]
        resources :reports, only: [ :show ]
      end
    end
  end


  # admin console
  namespace :admin do
  end


  # website
  scope module: :site do
    resources :groups, as: :site_groups, path: "welcome/teams", only: :create
    # do
    #   get "join", on: :member
    # end
    get   "homepage" => "pages#home"
    match "/"        => "pages#coming_soon"
  end

  root to: "site/pages#coming_soon"
end

=begin
  resources :groups, :path => "teams", path_names: { edit: :settings } do
    member do
      get  "join"
      get  "members/join" => "groups#add_member",     as: :add_member
      put  "leave"        => "groups#remove_member",  as: :remove_member
      post "rounds/start" => "groups#start_round",    as: :start_round
      get  "current"      => "groups#current_cycle",  as: :current_cycle
    end
    resources :cycles, only: [ :show, :index ] do
      put "payment_made" => "cycles#payment_made", as: :payment_made
    end
    resources :invites, only: [ :new, :create ]
    resources :members, only: [ :show, :index ]
    resources :memberships, only: :update_multiple do
      put "update_multiple", on: :collection
    end
  end
=end

=begin
  namespace :accounts, :path => "/hub" do
    resources :groups,        :only   => [ :index, :new, :create ],  :path => "teams"
    resources :cycles,        :only   => :index
    resources :notifications, :only   => :index
    resources :messages,      :except => [ :edit, :update ]

    root :to => "accounts#show", :as => :hub
  end
=end

# get     '/login'        => 'auth/bank_admins/sessions#new',         :as => :new_bank_admin_session
# post    '/login'        => 'auth/bank_admins/sessions#create',      :as => :bank_admin_session
# delete  '/logout'       => 'auth/bank_admins/sessions#destroy',     :as => :destroy_bank_admin_session
# get     '/account'      => 'auth/bank_admins/registrations#show',   :as => :bank_admin_registration
# get     '/account/settings' => 'auth/bank_admins/registrations#edit',   :as => :edit_bank_admin_registration
# put     '/account'      => 'auth/bank_admins/registrations#update'
# post    '/account'      => 'auth/bank_admins/registrations#create', :as => :bank_admin_registration

app/controllers/site/pages_controller.rb
class Site::PagesController < ApplicationController

  layout 'app'


  def coming_soon
    EmailSignup.create(email: params[:email]) if request.post?

    render layout: nil
  end


  def home
    @group = Group.new
  end


  def login_or_register
    @group = Group.find(params[:id])
  end

end

app/helpers/site/pages_helper.rb
module Site::PagesHelper
end

app/views/site/pages/coming_soon.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Coming Soon</title>
<link href="/assets/coming-soon/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/assets/coming-soon/jquery.min.js"></script>
<script type="text/javascript" src="/assets/coming-soon/cufon-yui.js"></script>
<script type="text/javascript" src="/assets/coming-soon/Bebas_400.font.js"></script>
<script type="text/javascript" src="/assets/coming-soon/Bell_Gothic_Std_300.font.js"></script>
<script type="text/javascript">
	Cufon.replace('a.logo', {fontFamily: 'Bebas'});
	Cufon.replace('a.logo span', {fontFamily: 'Bell Gothic Std'});
</script>

</head>
<body>
<div class="main_container">
	<div class="header">
		<a class="logo" href="#">MoneyTeam$<span>who's got your back?</span></a>
	</div>
	<div class="content">
		<h1>hello.<span>It's happening real soon :)</span></h1>
		<div class="right_side">
                  <!-- <p>// <a href="#">info@the.money.team.com</a><br/>// 506-200-5871</p> -->
                  <p><a href="#">&nbsp;</a><br/>&nbsp;</p>
			<ul class="s_icons">
				<li class="fb"><a href="#"></a></li>
				<li class="tw"><a href="#"></a></li>
				<li class="in"><a href="#"></a></li>
			</ul>
		</div>
	</div>
	<form action="/" method="post" class="email">
		<input type="text" name="email" class="field" onfocus="if(this.value=='Get Notified (Email Address)') this.value='';" onblur="if(this.value=='' || this.value==' ') this.value='Get Notified (Email Address)';" value="Get Notified (Email Address)" />
		<input type="button" class="submit" />
	</form>

</div>
</body>
</html>

app/views/site/pages/home.html.erb
home page

create group (new group form) => register (new user form) => view group



<%= flash.inspect %>

<%= form_for @group, url: site_groups_path do |f| -%>
  <p> Group Name: <%= f.text_field :name %> </p>
  <p> Each member pays <%= f.text_field :cycle_amount %> </p>
  <p> every <%= f.text_field :payment_cycle_quantity %>
      <%= f.select :payment_cycle_unit,
        options_for_select(Group.pretty_cycle_units, selected: "months") %> </p>
  <p> <%= f.submit "Save", class: "btn btn-primary" %> </p>
<% end -%>